#INCLUDE "P16F877A.INC"
	  
__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_OFF & _BODEN_OFF & _LVP_OFF & _HS_OSC	  
	  
CHECK EQU 0X20	  
COUNTERB EQU 0X21
CONTROL EQU 0X22
IMCOUNTER EQU 0X23
RECIEVED EQU 0X24
ADDRESS EQU 0X25
ANTIADDRESS EQU 0X26
COMMAND EQU 0X27
ANTICOMMAND EQU 0X28
 
RES_VECT  CODE    0x00      ; processor reset vector
	  GOTO    CONFI     ; go to beginning of program
  
INT_VECT  CODE 0X04	    ; interrupt vector
	  GOTO    ISR	    ; go to interrupt service routine 	
	  
ISEQUAL MACRO CHECK,THING
	MOVF THING,W
	SUBLW CHECK
	BTFSS STATUS,Z
	BCF CONTROL,1	    ;YA3NE NOT EQUAL SO FALSE BOOL
	BTFSC STATUS,Z
	BSF CONTROL,1	    ;YA3NE EQUAL SO TRUE BOOL
	ENDM
	
CONFI	BSF STATUS,RP0
	CLRF TRISB
	BSF TRISB,0	    ;PORT B OUTPUT EXCEPT FIRST BIT
	CLRF TRISD	    ;PORT D OUTPUT
	CLRF OPTION_REG
	BSF OPTION_REG,6    ; INTERRUPT ON RISING EDGE
	MOVLW H'90'	    ;GIE ENABLED // TMR0IE DISABLED //INTE ENABLED 
	MOVWF INTCON
	BCF STATUS,RP0
	MOVLW H'FF'
	MOVWF PORTD
	CLRF COUNTERB
	CLRF CONTROL
	CLRF IMCOUNTER
	CLRF RECIEVED
	CLRF CHECK
	GOTO MAIN
	
ISR	BCF INTCON,GIE		;DISABLES ALL INTERRUPTS
	
	BTFSC INTCON,INTF	;IF SIGNAL INTERRUPT
	GOTO SIGNALINT
	
	INCF COUNTERB,F		;ELSE TIME INTERRUPT
	
	ISEQUAL D'30',COUNTERB	;IGNORE ACTIVATED AT LIMIT
	BTFSC CONTROL,1
	BCF INTCON,TMR0IE	;DISABLES TIMER INTERRUPT
	BTFSC CONTROL,1
	CLRF COUNTERB		;CLEARS COUNTERB
	
	BCF INTCON,TMR0IF	;CLEARS TIMER INTERRUPT FLAG
	RETFIE
	
SIGNALINT   BSF INTCON,TMR0IE	;ENABLES TIMER INTERRUPT FLAG BECAUSE IT IS INTIALLY DISABLED
	
	  BTFSC CONTROL,0	;BIT ZERO OF CONTROL IS INITIAL MESSAGE
	  GOTO IMR
	  
	  ISEQUAL D'26',COUNTERB    ;CHECK FOR START PULSE
	  BTFSC CONTROL,1
	  BSF CONTROL,0		    ;ACTIVATE INITIAL MESSAGE ROUTINE
	  	 
RANDEVU   CLRF COUNTERB		    ;CLEARS COUNTERB
	  BCF INTCON,TMR0IF	    ;CLEARS TIMER INTERRUPT FLAG
	  BCF INTCON,INTF	    ;CLEARS SIGNAL INTERRUPT FLAG
	  CLRF TMR0		    ;CLEARS TIMER TMR0
	  RETFIE
	  
IMR	INCF IMCOUNTER,F
	  
	ISEQUAL D'2',COUNTERB     ;CHECK IF IT IS LOGIC ZERO
	BTFSC CONTROL,1		 
	BCF RECIEVED,0		 ;IF TRUE LOGIC ZERO
	BTFSS CONTROL,1	    
	BSF RECIEVED,0		 ;IF FALSE LOGIC ONE

	ISEQUAL D'8',IMCOUNTER 
	BTFSS CONTROL,1	;SKIP IF TRUE
	GOTO CIAA
	MOVF RECIEVED,W
	MOVWF ADDRESS	
	CLRF  RECIEVED
	GOTO RANDEVU
	
CIAA	ISEQUAL D'16',IMCOUNTER
	BTFSS CONTROL,1	;SKIP IF TRUE
	GOTO CIC
	MOVF RECIEVED,W
	MOVWF ANTIADDRESS	
	CLRF  RECIEVED
	GOTO RANDEVU
	
CIC	ISEQUAL D'24',IMCOUNTER
	BTFSS CONTROL,1 ;SKIP IF TRUE
	GOTO CIAC
	MOVF RECIEVED,W
	MOVWF COMMAND	
	CLRF  RECIEVED
	GOTO RANDEVU	
CIAC	ISEQUAL D'32',IMCOUNTER
	BTFSS CONTROL,1 ;SKIP IF TRUE
	GOTO DONE
	MOVF RECIEVED,W
	MOVWF ANTICOMMAND		
	CLRF RECIEVED
	GOTO ENDIMR	
DONE	RLF RECIEVED,F
	GOTO RANDEVU 
	
ENDIMR	BCF CONTROL,0	;CLEAR IMR BIT 
	CLRF IMCOUNTER	;CLEAR IMCOUNTER	
	GOTO RANDEVU

MAIN	MOVF COMMAND,W
	MOVWF PORTD
	GOTO MAIN
END
